name: gh-react-test
on: workflow_dispatch
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: code
              uses: actions/checkout@v3
            - name: Install 
              uses: actions/setup-node@v3
              with:
                node-version: 22
            - name: install npm
              run: npm install
            - name: npm test 
              run: npm run test